language: android
dist: trusty

android:
  components:
     - android-28
     - tools
     - build-tools-28.0.0
     - extra-android-m2repository
     - extra-android-m2repository
     - extra-google-google_play_services
     - $ANDROID_TARGET
     - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

script:
     - ./gradlew build jacocoTestReport

before_install:
     - chmod +x gradlew

after_success: 
     - bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}

licenses:
     - 'android-sdk-license-.+'
     - 'google-gdk-license-.+'


