language: android
dist: trusty

env:
  global:
    - ANDROID_TARGET=android-28
    - CODECOV_TOKEN=52bcf07f-611f-47cc-81f5-e86d77d6fcb7

android:
  components:
     - android-28
     - tools
     - build-tools-28.0.0
     - extra-android-m2repository
     - extra-android-m2repository
     - extra-google-google_play_services
     - $ANDROID_TARGET
     - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

script:
     - ./gradlew build jacocoTestReport

before_install:
     - chmod +x gradlew

after_success: 
     - bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}


