language: android
dist: trusty

env:
  global:
    - ANDROID_TARGET=android-28
    - ANDROID_ABI=armeabi-v7a
    - CODECOV_TOKEN=db8e7acd-da0d-45c4-8843-44be814b73cf

android:
  components:
     - android-28
     - tools
     - platform-tools
     - build-tools-28.0.0
     - extra-android-m2repository
     - extra-android-m2repository
     - extra-google-google_play_services
     - $ANDROID_TARGET
     - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

licenses:
     - 'android-sdk-license-.+'

script:
     - ./gradlew build jacocoTestReport

before_install:
     - chmod +x gradlew
     - yes | sdkmanager "platforms;android-28"
     - yes | sdkmanager --update

after_success:
     - bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

