version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Setup Environment Variables
          command: |
            echo "f93aa7c8-1579-4687-870f-cc6e08a93316" >> $CODECOV_TOKEN
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint
      - run:
          name: Generate Maven Artifacts
          command: ./gradlew assembleDebug
workflows:
  version: 2
  build:
    steps:
      - codecov/upload:
          file: coverage/*.json
          token: "f93aa7c8-1579-4687-870f-cc6e08a93316"
      - run:
          name: send to codecov
          command: "bash <(curl -s https://codecov.io/bash) -t f93aa7c8-1579-4687-870f-cc6e08a93316"
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
